name: webapp_models
description: Contains models for web app.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  protobuf: ^2.0.0
  built_value: ^8.1.3
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  built_value_generator: ^8.1.3