// Code generated by "stringer -type=ResultStatusCode"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-200]
	_ = x[NOT_FOUND-404]
	_ = x[INVALID_ARGUMENT-400]
	_ = x[UNAUTHORIZED-401]
	_ = x[PERMISSION_DENIED-403]
	_ = x[ALREADY_EXISTS-409]
	_ = x[RESOURCE_EXHAUSTED-410]
	_ = x[UNKNOWN-500]
	_ = x[INTERNAL_SERVER_ERROR-500]
}

const (
	_ResultStatusCode_name_0 = "OK"
	_ResultStatusCode_name_1 = "INVALID_ARGUMENTUNAUTHORIZED"
	_ResultStatusCode_name_2 = "PERMISSION_DENIEDNOT_FOUND"
	_ResultStatusCode_name_3 = "ALREADY_EXISTSRESOURCE_EXHAUSTED"
	_ResultStatusCode_name_4 = "UNKNOWN"
)

var (
	_ResultStatusCode_index_1 = [...]uint8{0, 16, 28}
	_ResultStatusCode_index_2 = [...]uint8{0, 17, 26}
	_ResultStatusCode_index_3 = [...]uint8{0, 14, 32}
)

func (i ResultStatusCode) String() string {
	switch {
	case i == 200:
		return _ResultStatusCode_name_0
	case 400 <= i && i <= 401:
		i -= 400
		return _ResultStatusCode_name_1[_ResultStatusCode_index_1[i]:_ResultStatusCode_index_1[i+1]]
	case 403 <= i && i <= 404:
		i -= 403
		return _ResultStatusCode_name_2[_ResultStatusCode_index_2[i]:_ResultStatusCode_index_2[i+1]]
	case 409 <= i && i <= 410:
		i -= 409
		return _ResultStatusCode_name_3[_ResultStatusCode_index_3[i]:_ResultStatusCode_index_3[i+1]]
	case i == 500:
		return _ResultStatusCode_name_4
	default:
		return "ResultStatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
