name: webapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^2.4.2
  dio: ^4.0.0
  url_strategy: ^0.2.0
  flutter_form_builder: ^7.0.0-beta.0
  form_builder_validators: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.4

dependency_overrides: 
  auto_route:
    git:
      url: https://github.com/TomasWeg/auto_route_library.git
      ref: master
      path: auto_route
  auto_route_generator:
    git:
      url: https://github.com/TomasWeg/auto_route_library.git
      ref: master
      path: auto_route_generator

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
